name: Publish

on:
    release:
        types:
            [published]

concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    publish_pypi:
        name: Publish package to PyPI
        runs-on: ubuntu-latest
        permissions:
            # IMPORTANT: this permission is mandatory for trusted publishing
            id-token: write
        steps:
        - name: Check out mis
          uses: actions/checkout@v6
          with:
            ref: ${{ github.ref }}
        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: "3.10"
        - name: Install Hatch
          run: |
            python -m pip install --upgrade pip
            pip install hatch
        - name: Build and publish package
          run: |
            hatch build
        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
        - name: Confirm deployment
          timeout-minutes: 5
          run: |
            VERSION=${GITHUB_REF#refs/tags/v}
            until pip download maximum-independent-set==$VERSION
            do
                echo "Failed to download from PyPI, will wait for upload and retry."
                sleep 1
            done

    public_docs:
        name: Publish docs to github pages
        runs-on: ubuntu-latest
        steps:
        - name: Checkout mis
          uses: actions/checkout@v6
        - name: Install JetBrains Mono font
          run: |
            sudo apt install -y wget unzip fontconfig
            wget https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
            unzip JetBrainsMono-2.304.zip -d JetBrainsMono
            mkdir -p /usr/share/fonts/truetype/jetbrains
            cp JetBrainsMono/fonts/ttf/*.ttf /usr/share/fonts/truetype/jetbrains/
            fc-cache -f -v
        - name: Install graphviz
          run: sudo apt-get install -y graphviz
        - name: Set up Python 3.10
          uses: actions/setup-python@v6
          with:
            python-version: '3.10'
        - name: Install Hatch
          run: |
            pip install hatch
        - name: Copy notebooks and test files to build docs
          run: |
            cp examples/*.ipynb docs/
            cp -r examples/datasets/ docs/
        - name: Deploy docs
          run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git fetch origin gh-pages
            hatch -v run docs:mike deploy --push --update-aliases ${{ github.ref_name }} latest
