name: Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_mis_ubuntu:
    name: Run unit/integration tests (Ubuntu)
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout mis
      uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: |
        pip install hatch
    - name: Run tests
      run: |
        hatch -v run test
        hatch -v run test_readme
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: pasqal-io/maximum-independent-set

  test_mis_windows:
    name: Run unit/integration tests (Windows)
    # Testing Windows separately and with fewer versions
    # of Python, as:
    # - it's much slower;
    # - generating illustrations in markdown seems to freeze
    #   under Windows (it's waiting for user interaction to
    #   close the window), so we want to only test documentation
    #   snippets under Unix.
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout mis
      uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: |
        pip install hatch
    - name: Run tests
      run: |
        hatch -v run test

  test_doc:
    name: Test docs build
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout MIS
      uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: |
        pip install hatch
    - name: Run tests
      run: |
        hatch -v run docs:build

  test_notebook:
    name: Run the Jupyter notebook tutorial (Unix)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout mis
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Run notebooks
        run: |
          hatch run pip install jupyter
          for tutorial in examples/tutorial*.ipynb; do
            hatch run jupyter execute "$tutorial";
          done

  test_notebook_windows:
    name: Run the Jupyter notebook tutorial (Windows)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.10"]
    steps:
      - name: Checkout mis
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Run notebook
        run: |
          hatch run pip install jupyter
          $files = Get-ChildItem -Path examples -Include *.ipynb
          foreach($tutorial in $files) {
            hatch run jupyter execute "$tutorial"
          }
